let currentLanguage = "en";

const translations = {
    es: {
        nav_about: "Sobre mí",
        nav_projects: "Proyectos",
        nav_featured: "Destacados",
        nav_demos: "Demos",
        nav_experience: "Experiencia",
        nav_education: "Educación",
        nav_certifications: "Certificaciones",
        nav_skills: "Skills",
        nav_contact: "Contacto",
        hero_kicker: "INGENIERIA IA · LLMOPS · CLOUD",
        hero_title: "Ingeniero IA y MLOps",
        hero_description: "Diseno y despliego productos de IA confiables, desde la experimentacion de modelos hasta infraestructura escalable en produccion.",
        hero_cta_cv: "Descargar CV",
        hero_cta_contact: "Contactarme",
        metric_years: "Anos en IA",
        metric_demos: "Demos ML en vivo",
        metric_tools: "Herramientas en produccion",
        about_title: "Sobre mí",
        about_text: "Ingeniero Informatico especializado en Computacion, un campo que me entusiasma porque permite convertir ideas en soluciones reales. Siempre me ha fascinado entender como funcionan las cosas, y la computacion me ha dado las herramientas para explorar y crear. Me encanta profundizar en ramas como inteligencia artificial, machine learning y optimizacion de algoritmos, buscando siempre la forma mas eficiente de resolver problemas.",
        about_card1_title: "Entrega IA end-to-end",
        about_card1_text: "Desde datos y experimentacion hasta despliegue, monitorizacion e iteracion en produccion.",
        about_card2_title: "Mentalidad MLOps",
        about_card2_text: "Infraestructura como codigo, reproducibilidad, CI/CD y workflows cloud escalables.",
        about_card3_title: "Impacto de negocio",
        about_card3_text: "Priorizo soluciones practicas que mejoran resultados y eficiencia de los equipos.",
        projects_title: "Proyectos",
        featured_title: "Proyectos destacados",
        featured_subtitle: "Dos proyectos que representan mejor mi enfoque de ingenieria IA y MLOps.",
        featured_1_title: "Deteccion de polipos con Deep Learning",
        featured_1_text: "Vision por computador aplicada a mejorar la deteccion de enfermedades gastrointestinales con workflows de investigacion robustos.",
        featured_2_title: "DataScience Bootcamp",
        featured_2_text: "Ruta estructurada de Python, SQL, machine learning y proyectos practicos con impacto real.",
        demos_title: "Demos en vivo 🎮",
        demos_subtitle: "Demos interactivas ejecutandose en tu navegador.",
        demos_filter_all: "Todas",
        demos_filter_ml: "ML",
        demos_filter_cv: "Vision por Computador",
        demos_filter_llm: "LLM",
        demos_expand_all: "Expandir todo",
        demos_collapse_all: "Contraer todo",
        demo_concept_overview: "Resumen del concepto",
        demo_key_highlights: "Puntos clave",
        demo_kmeans_title: "K-Means Clustering",
        demo_kmeans_subtitle: "Algoritmo de agrupamiento no supervisado",
        demo_kmeans_concept: "K-Means es un algoritmo de Machine Learning no supervisado que divide datos sin etiqueta en K clusters distintos segun similitud de caracteristicas (distancia euclidea).",
        demo_kmeans_li1: "Refinamiento iterativo de centroides.",
        demo_kmeans_li2: "Minimiza la varianza intra-cluster (inercia).",
        demo_kmeans_li3: "Casos de uso: segmentacion de clientes, deteccion de anomalias y compresion de imagen.",
        demo_kmeans_btn_new: "Nuevos datos",
        demo_kmeans_btn_step: "Ejecutar paso",
        demo_tokenizer_title: "Tokenizador de texto",
        demo_tokenizer_subtitle: "Preprocesado NLP de texto a vector",
        demo_tokenizer_concept: "Los LLMs no leen texto caracter a caracter. Usan tokenizadores para dividir texto en sub-palabras o fragmentos, asignando a cada uno un token ID unico.",
        demo_tokenizer_li1: "Simula tokenizacion de sub-palabras (BPE o WordPiece).",
        demo_tokenizer_li2: "Transforma texto humano en tensores numericos para IA.",
        demo_tokenizer_li3: "Relevancia: clave para Prompt Engineering y pipelines de inferencia LLMOps.",
        demo_tokenizer_placeholder: "Escribe una frase aqui...",
        demo_tokenizer_btn: "Generar tokens",
        demo_od_title: "Deteccion de objetos",
        demo_od_subtitle: "Simulacion de inferencia en Vision por Computador",
        demo_od_concept: "Simula la salida de redes neuronales convolucionales (CNN) como YOLO o Faster R-CNN. El modelo identifica regiones de interes, aplica bounding boxes y asigna una probabilidad de clasificacion.",
        demo_od_li1: "Extraccion espacial de caracteristicas y anchor boxes.",
        demo_od_li2: "Umbrales de confianza para predicciones.",
        demo_od_li3: "Casos de uso: imagen medica (ej. deteccion de polipos) y conduccion autonoma.",
        demo_od_btn_run: "Ejecutar inferencia",
        demo_od_btn_clear: "Limpiar",
        demo_gd_title: "Gradient Descent",
        demo_gd_subtitle: "Optimizacion matematica de funciones de perdida",
        demo_gd_concept: "Algoritmo de optimizacion central en Deep Learning. Actualiza pesos del modelo iterativamente moviendose en la direccion de mayor descenso (gradiente negativo) del landscape de la perdida.",
        demo_gd_li1: "Visualiza una tasa de aprendizaje aplicada a una derivada.",
        demo_gd_li2: "Busca alcanzar el minimo global.",
        demo_gd_li3: "Relevancia: backpropagation en redes neuronales.",
        demo_gd_btn_step: "Iterar (paso)",
        demo_gd_btn_reset: "Reiniciar",
        demo_af_title: "Funciones de activacion",
        demo_af_subtitle: "Introduciendo no linealidad en redes neuronales",
        demo_af_concept: "Sin funciones de activacion, una red neuronal profunda seria solo una regresion lineal. Estas funciones deciden si una neurona se activa, permitiendo aprender patrones complejos.",
        demo_af_li1: "ReLU: rapida y ayuda a prevenir el desvanecimiento del gradiente.",
        demo_af_li2: "Sigmoid/Tanh: utiles para probabilidades pero propensas a saturacion.",
        demo_af_opt_relu: "ReLU (Rectified Linear Unit)",
        demo_af_opt_sigmoid: "Funcion sigmoide",
        demo_af_opt_tanh: "Tangente hiperbolica (Tanh)",
        demo_rag_title: "Arquitectura RAG",
        demo_rag_subtitle: "Simulador de Retrieval-Augmented Generation",
        demo_rag_concept: "RAG mejora los LLM conectandolos a bases de conocimiento externas. Antes de responder, el sistema consulta una base vectorial (como Pinecone o FAISS) para recuperar contexto factual.",
        demo_rag_li1: "Reduce alucinaciones al basar respuestas en datos.",
        demo_rag_li2: "Combina busqueda semantica (embeddings) con generacion.",
        demo_rag_li3: "Relevancia: sistemas IA empresariales y chatbots con datos privados.",
        demo_rag_knowledge: "Conocimiento en DB vectorial:",
        demo_rag_placeholder: "Pregunta algo sobre Raúl...",
        demo_rag_btn: "Ejecutar pipeline RAG",
        demo_rag_step1: "1. Contexto recuperado:",
        demo_rag_step2: "2. Salida del LLM:",
        demo_cnn_title: "Convoluciones CNN",
        demo_cnn_subtitle: "Filtrado matematico de imagenes",
        demo_cnn_concept: "Las redes convolucionales (CNN) procesan imagenes deslizando matrices matematicas llamadas kernels (filtros) sobre los pixeles para extraer rasgos espaciales como bordes, esquinas y texturas.",
        demo_cnn_li1: "Reduce dimensiones espaciales capturando rasgos profundos.",
        demo_cnn_li2: "Operacion central en modelos como ResNet y YOLO.",
        demo_cnn_li3: "Relevancia: deteccion de polipos (imagen medica) y conduccion autonoma.",
        demo_cnn_btn_original: "Original",
        demo_cnn_btn_edge: "Deteccion de bordes",
        demo_cnn_btn_sharpen: "Enfocar",
        experience_title: "Experiencia profesional 🧑‍💻",
        exp1_title: "Ingeniero MLOps en Multiverse Computing",
        exp1_duration: "Duracion: Feb. 2026 - Presente",
        exp1_location: "Ubicacion: Zaragoza, Aragon, Espana · Hibrido",
        exp1_desc: "Como contribuidor principal del proyecto Multiverse Foundry, una aplicacion empresarial todo-en-uno, integro compresion de modelos (via CompactifAI), pipelines de fine-tuning y despliegue. Mis responsabilidades incluyen la gestion de GPUs y la orquestacion de clusters con Kubernetes, SkyPilot y Coder, asi como la operacion y escalado de infraestructura cloud en AWS (EC2, S3, ECR) para soportar workflows robustos de machine learning. Ademas, automatizo el ciclo de vida de aplicaciones con LLM empaquetandolas con Helm y gestionando flujos GitOps con ArgoCD.",
        exp2_title: "Ingeniero de Inteligencia Artificial en Atrebo",
        exp2_duration: "Duracion: Jul. 2025 - Feb. 2026",
        exp2_location: "Ubicacion: Sevilla, Andalucia, Espana · Hibrido",
        exp2_desc: "Ingeniero de Inteligencia Artificial en Atrebo: desarrollo y despliegue de soluciones IA empresariales usando LLMs y Retrieval-Augmented Generation (RAG). Responsabilidades en prompt engineering, fine-tuning y optimizacion de modelos (quantization, distillation, LoRA), integracion de pipelines escalables (LangChain, FastAPI, Docker, Kubernetes) y evaluacion con metricas avanzadas. Experiencia con practicas MLOps (MLflow, monitorizacion, reproducibilidad), bases vectoriales (FAISS, Pinecone) y servicios cloud de IA, entregando sistemas inteligentes listos para produccion.",
        exp3_title: "Becario de Inteligencia Artificial en NTT DATA Europe & Latam",
        exp3_duration: "Duracion: Jul. 2024 - Sept. 2024 (3 meses)",
        exp3_location: "Ubicacion: Sevilla, Andalucia, Espana · Hibrido",
        exp3_desc: "Impulse la transformacion digital en el sector energetico desarrollando aplicaciones cliente de alto rendimiento en Python y optimizando procesos ETL. Mi trabajo abarco arquitectura tecnica, mantenimiento de sistemas y orquestacion de despliegues en produccion bajo estandares estrictos de control de versiones. Gracias al conocimiento del dominio, trabaje directamente con usuarios finales para disenar soluciones basadas en Machine Learning, transformando requisitos complejos en soluciones escalables y eficientes.",
        education_title: "Educacion 🎓",
        edu1_title: "Titulo: Master en Ingenieria Informatica - Big Data y Cloud Computing",
        edu1_duration: "Duracion: Oct. 2025 - Presente",
        edu2_title: "Titulo: Grado en Ingenieria Informatica, Ciencias de la Computacion",
        edu2_duration: "Duracion: Sept. 2021 - Jul. 2025",
        edu3_title: "Titulo: B1, Teaching English as a Foreign Language",
        edu3_duration: "Duracion: Ene. 2018 - Jun. 2018",
        certifications_title: "Licencias y certificaciones 📜",
        cert1_issue: "Emitido: Ene. 2026",
        cert1_id: "ID de credencial: https://www.scrum.org/certificates/1283195",
        cert2_issue: "Emitido: Nov. 2025",
        cert2_id: "ID de credencial: ENELD3KY5ALY",
        cert3_issue: "Emitido: Ago. 2024",
        cert3_id: "ID de credencial: UC-29308443-ca19-4a9b-acb7-455802922f2d",
        skills_title: "Skills",
        skills_group_1: "IA Generativa y LLMs",
        skills_group_2: "MLOps y Arquitectura Cloud",
        skills_group_3: "Ecosistema Big Data",
        skills_group_4: "Data Science y Machine Learning",
        skills_group_5: "Lenguajes de Programacion",
        skills_group_6: "Herramientas",
        contact_title: "Contacto",
        form_name_label: "Nombre:",
        form_name_placeholder: "Tu nombre completo",
        form_email_label: "Email:",
        form_email_placeholder: "tu@email.com",
        form_message_label: "Mensaje:",
        form_message_placeholder: "Cuéntame sobre tu proyecto u oportunidad...",
        form_submit: "Enviar mensaje",
        footer_copy: "Copyright © 2025 - Raúl Jiménez",
        contact_success: "Mensaje enviado correctamente",
        contact_error: "Error al enviar el mensaje"
    },
    en: {
        nav_about: "About Me",
        nav_projects: "Projects",
        nav_featured: "Featured",
        nav_demos: "Demos",
        nav_experience: "Experience",
        nav_education: "Education",
        nav_certifications: "Certifications",
        nav_skills: "Skills",
        nav_contact: "Contact",
        hero_kicker: "AI ENGINEERING · LLMOPS · CLOUD",
        hero_title: "AI & MLOps Engineer",
        hero_description: "I design and deploy reliable AI products, from model experimentation to scalable production infrastructure.",
        hero_cta_cv: "Download CV",
        hero_cta_contact: "Contact me",
        metric_years: "Years in AI",
        metric_demos: "Live ML demos",
        metric_tools: "Production tools",
        about_title: "About Me",
        about_text: "Computer Engineer specializing in Computation, a field that excites me because it allows me to turn ideas into real solutions. I have always been fascinated by understanding how things work, and computing has given me the tools to explore and create. I enjoy diving into branches such as artificial intelligence, machine learning, and algorithm optimization while looking for efficient solutions.",
        about_card1_title: "End-to-end AI delivery",
        about_card1_text: "From data and experimentation to deployment, monitoring, and production iteration.",
        about_card2_title: "Strong MLOps mindset",
        about_card2_text: "Infrastructure as code, reproducibility, CI/CD, and scalable cloud workflows.",
        about_card3_title: "Business impact first",
        about_card3_text: "I focus on practical solutions that improve outcomes and team efficiency.",
        projects_title: "Projects",
        featured_title: "Featured Projects",
        featured_subtitle: "Two projects that best represent my AI engineering and MLOps approach.",
        featured_1_title: "Polyp Detection with Deep Learning",
        featured_1_text: "Applied computer vision to improve gastrointestinal disease detection with robust research workflows.",
        featured_2_title: "DataScience Bootcamp",
        featured_2_text: "A structured path covering Python, SQL, machine learning, and practical projects for real-world impact.",
        demos_title: "Live Demos 🎮",
        demos_subtitle: "Interactive demos running in your browser.",
        demos_filter_all: "All",
        demos_filter_ml: "ML",
        demos_filter_cv: "Computer Vision",
        demos_filter_llm: "LLM",
        demos_expand_all: "Expand All",
        demos_collapse_all: "Collapse All",
        demo_concept_overview: "Concept Overview",
        demo_key_highlights: "Key Highlights",
        demo_kmeans_title: "K-Means Clustering",
        demo_kmeans_subtitle: "Unsupervised grouping algorithm",
        demo_kmeans_concept: "K-Means is an unsupervised Machine Learning algorithm used to partition unlabeled data into K distinct clusters based on feature similarity (Euclidean distance).",
        demo_kmeans_li1: "Iterative refinement of cluster centroids.",
        demo_kmeans_li2: "Minimizes within-cluster variance (inertia).",
        demo_kmeans_li3: "Use cases: Customer segmentation, anomaly detection, and image compression.",
        demo_kmeans_btn_new: "New Data",
        demo_kmeans_btn_step: "Run Step",
        demo_tokenizer_title: "Text Tokenizer",
        demo_tokenizer_subtitle: "NLP text-to-vector preprocessing",
        demo_tokenizer_concept: "Large Language Models (LLMs) do not read text character by character. They use tokenizers to break text into sub-words or chunks, mapping each to a unique token ID.",
        demo_tokenizer_li1: "Simulates sub-word tokenization (like BPE or WordPiece).",
        demo_tokenizer_li2: "Transforms human text into numeric tensors for AI.",
        demo_tokenizer_li3: "Relevance: Crucial for Prompt Engineering and LLMOps inference pipelines.",
        demo_tokenizer_placeholder: "Type a sentence here...",
        demo_tokenizer_btn: "Generate Tokens",
        demo_od_title: "Object Detection",
        demo_od_subtitle: "Computer Vision inference simulation",
        demo_od_concept: "Simulates the output of Convolutional Neural Networks (CNNs) like YOLO or Faster R-CNN. The model identifies regions of interest, applies bounding boxes, and assigns a classification probability.",
        demo_od_li1: "Spatial feature extraction and anchor boxes.",
        demo_od_li2: "Confidence thresholds for predictions.",
        demo_od_li3: "Use cases: Medical imaging (e.g., polyp detection), autonomous driving.",
        demo_od_btn_run: "Run Inference",
        demo_od_btn_clear: "Clear",
        demo_gd_title: "Gradient Descent",
        demo_gd_subtitle: "Mathematical optimization for loss functions",
        demo_gd_concept: "The core optimization algorithm behind Deep Learning. It updates model weights iteratively by moving in the direction of steepest descent (negative gradient) of the loss landscape.",
        demo_gd_li1: "Visualizes a learning rate applied to a derivative.",
        demo_gd_li2: "Strives to find the global minimum.",
        demo_gd_li3: "Relevance: Backpropagation in Neural Networks.",
        demo_gd_btn_step: "Iterate (Step)",
        demo_gd_btn_reset: "Reset",
        demo_af_title: "Activation Functions",
        demo_af_subtitle: "Introducing non-linearity in Neural Nets",
        demo_af_concept: "Without activation functions, a deep neural network would simply be a linear regression model. These functions decide whether a neuron should fire, enabling the network to learn complex patterns.",
        demo_af_li1: "ReLU: Fast and helps prevent vanishing gradients.",
        demo_af_li2: "Sigmoid/Tanh: Great for probabilities but prone to saturation.",
        demo_af_opt_relu: "ReLU (Rectified Linear Unit)",
        demo_af_opt_sigmoid: "Sigmoid Function",
        demo_af_opt_tanh: "Hyperbolic Tangent (Tanh)",
        demo_rag_title: "RAG Architecture",
        demo_rag_subtitle: "Retrieval-Augmented Generation Simulator",
        demo_rag_concept: "RAG enhances LLMs by connecting them to external knowledge bases. Before answering, the system queries a vector database (like Pinecone or FAISS) to retrieve factual context.",
        demo_rag_li1: "Reduces hallucinations by grounding answers in data.",
        demo_rag_li2: "Combines semantic search (embeddings) with generation.",
        demo_rag_li3: "Relevance: Enterprise AI systems and private-data chatbots.",
        demo_rag_knowledge: "Vector DB Knowledge:",
        demo_rag_placeholder: "Ask about Raúl...",
        demo_rag_btn: "Run RAG Pipeline",
        demo_rag_step1: "1. Context Retrieved:",
        demo_rag_step2: "2. LLM Output:",
        demo_cnn_title: "CNN Convolutions",
        demo_cnn_subtitle: "Mathematical Image Filtering",
        demo_cnn_concept: "Convolutional Neural Networks (CNNs) process images by sliding mathematical matrices called kernels (or filters) over pixels to extract spatial features like edges, corners, and textures.",
        demo_cnn_li1: "Reduces spatial dimensions while capturing deep features.",
        demo_cnn_li2: "Core operation behind models like ResNet and YOLO.",
        demo_cnn_li3: "Relevance: Polyp detection (medical imaging) and autonomous driving.",
        demo_cnn_btn_original: "Original",
        demo_cnn_btn_edge: "Edge Detection",
        demo_cnn_btn_sharpen: "Sharpen",
        experience_title: "Work Experience 🧑‍💻",
        exp1_title: "MLOps Engineer at Multiverse Computing",
        exp1_duration: "Duration: Feb. 2026 - Present",
        exp1_location: "Location: Zaragoza, Aragon, Spain · Hybrid",
        exp1_desc: "As a core contributor to the Multiverse Foundry project—an all-in-one enterprise application—I integrate model compression (via CompactifAI), fine-tuning, and deployment pipelines. My responsibilities include managing GPU allocation and cluster orchestration utilizing Kubernetes, SkyPilot, and Coder, as well as operating and scaling cloud infrastructure on AWS (EC2, S3, ECR) to support robust machine learning workflows. Additionally, I focus on automating the lifecycle of large language model (LLM) applications by packaging them with Helm and managing GitOps workflows with ArgoCD.",
        exp2_title: "Artificial Intelligence Engineer at Atrebo",
        exp2_duration: "Duration: Jul. 2025 - Feb. 2026",
        exp2_location: "Location: Seville, Andalusia, Spain · Hybrid",
        exp2_desc: "Artificial Intelligence Engineer at Atrebo: Development and deployment of enterprise AI solutions using Large Language Models (LLMs) and Retrieval-Augmented Generation (RAG). Responsibilities included prompt engineering, fine-tuning, and model optimization (quantization, distillation, LoRA), integration of scalable pipelines (LangChain, FastAPI, Docker, Kubernetes), and model evaluation with advanced metrics. Experience with MLOps practices (MLflow, monitoring, reproducibility), vector databases (FAISS, Pinecone), and cloud AI services, delivering production-ready intelligent systems.",
        exp3_title: "Artificial Intelligence Intern at NTT DATA Europe & Latam",
        exp3_duration: "Duration: Jul. 2024 - Sept. 2024 (3 months)",
        exp3_location: "Location: Seville, Andalusia, Spain · Hybrid",
        exp3_desc: "I drive digital transformation in the energy sector by developing high-performance client applications in Python and optimising ETL processes. My work ranges from technical architecture and system maintenance to orchestrating deployments in production environments under strict version control standards. Thanks to a deep understanding of the business domain, I work directly with end users to design Machine Learning-based solutions, transforming complex requirements into scalable and efficient solutions.",
        education_title: "Education 🎓",
        edu1_title: "Title: Master's Degree in Computer Engineering - Big Data & Cloud Computing",
        edu1_duration: "Duration: Oct. 2025 - Present",
        edu2_title: "Title: Bachelor’s Degree in Computer Engineering, Computational Science",
        edu2_duration: "Duration: Sept. 2021 - Jul. 2025",
        edu3_title: "Title: B1, Teaching English as a Foreign Language",
        edu3_duration: "Duration: Jan. 2018 - Jun. 2018",
        certifications_title: "Licenses and certifications 📜",
        cert1_issue: "Issued: Jan. 2026",
        cert1_id: "Credential ID: https://www.scrum.org/certificates/1283195",
        cert2_issue: "Issued: Nov. 2025",
        cert2_id: "Credential ID: ENELD3KY5ALY",
        cert3_issue: "Issued: Aug. 2024",
        cert3_id: "Credential ID: UC-29308443-ca19-4a9b-acb7-455802922f2d",
        skills_title: "Skills",
        skills_group_1: "Generative AI & LLMs",
        skills_group_2: "MLOps & Cloud Architecture",
        skills_group_3: "Big Data Ecosystem",
        skills_group_4: "Data Science & Machine Learning",
        skills_group_5: "Programming Languages",
        skills_group_6: "Tools",
        contact_title: "Contact",
        form_name_label: "Name:",
        form_name_placeholder: "Your full name",
        form_email_label: "Email:",
        form_email_placeholder: "your@email.com",
        form_message_label: "Message:",
        form_message_placeholder: "Tell me about your project or opportunity...",
        form_submit: "Send Message",
        footer_copy: "Copyright © 2025 - Raúl Jiménez",
        contact_success: "Message sent successfully",
        contact_error: "Error sending message"
    }
};

function setLanguage(lang) {
    const selectedLanguage = translations[lang] ? lang : currentLanguage;
    const dictionary = translations[selectedLanguage];
    currentLanguage = selectedLanguage;

    document.documentElement.lang = selectedLanguage;
    localStorage.setItem("portfolio-language", selectedLanguage);

    document.querySelectorAll("[data-i18n]").forEach((element) => {
        const key = element.getAttribute("data-i18n");
        if (dictionary[key]) {
            element.textContent = dictionary[key];
        }
    });

    document.querySelectorAll("[data-i18n-placeholder]").forEach((element) => {
        const key = element.getAttribute("data-i18n-placeholder");
        if (dictionary[key]) {
            element.setAttribute("placeholder", dictionary[key]);
        }
    });
}

function getTranslation(key) {
    const dictionary = translations[currentLanguage] || translations.en;
    return dictionary[key] || key;
}

window.setLanguage = setLanguage;
window.getTranslation = getTranslation;

document.addEventListener("DOMContentLoaded", () => {
    const preferredLanguage = localStorage.getItem("portfolio-language");
    setLanguage(preferredLanguage || "en");
});